sonar.projectKey=ScheduleMicroserviceBackend
sonar.working.directory=C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice
sonar.pullrequest.cache.basepath=C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice

5813F101-6DF5-421A-B342-1C8553F9F092.sonar.projectKey=ScheduleMicroserviceBackend:5813F101-6DF5-421A-B342-1C8553F9F092
5813F101-6DF5-421A-B342-1C8553F9F092.sonar.projectName=DataAccessLayer
5813F101-6DF5-421A-B342-1C8553F9F092.sonar.projectBaseDir=C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\DataAccessLayer
5813F101-6DF5-421A-B342-1C8553F9F092.sonar.sourceEncoding=utf-8
5813F101-6DF5-421A-B342-1C8553F9F092.sonar.sources=\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\DataAccessLayer\\DataBase\\DataBaseSettings.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\DataAccessLayer\\DataBase\\IDataBaseSettings.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\DataAccessLayer\\MappingConfig.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\DataAccessLayer\\Models\\ClinicServices.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\DataAccessLayer\\Models\\DTO\\ClinicServicesCreateDto.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\DataAccessLayer\\Models\\DTO\\ClinicServicesDto.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\DataAccessLayer\\Models\\DTO\\ScheduleAppointmentCreateDto.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\DataAccessLayer\\Models\\DTO\\ScheduleAppointmentDto.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\DataAccessLayer\\Models\\ScheduleAppointment.cs"

5813F101-6DF5-421A-B342-1C8553F9F092.sonar.coverage.exclusions=**/ClinicServices.cs,**/ScheduleAppointment.cs,**/MappingConfig.cs,**/DataBaseSettings.cs
5813F101-6DF5-421A-B342-1C8553F9F092.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\.sonarqube\\out\\0"
5813F101-6DF5-421A-B342-1C8553F9F092.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\.sonarqube\\out\\0\\Issues.json"

5813F101-6DF5-421A-B342-1C8553F9F092.sonar.working.directory=C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\.sonarqube\\out\\.sonar\\mod0
53E6540C-7C2B-4706-96B4-EDE4840EBD41.sonar.projectKey=ScheduleMicroserviceBackend:53E6540C-7C2B-4706-96B4-EDE4840EBD41
53E6540C-7C2B-4706-96B4-EDE4840EBD41.sonar.projectName=BusinessLogicLayer
53E6540C-7C2B-4706-96B4-EDE4840EBD41.sonar.projectBaseDir=C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\BusinessLogicLayer
53E6540C-7C2B-4706-96B4-EDE4840EBD41.sonar.sourceEncoding=utf-8
53E6540C-7C2B-4706-96B4-EDE4840EBD41.sonar.sources=\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\BusinessLogicLayer\\Services\\IServices\\IScheduleService.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\BusinessLogicLayer\\Services\\ScheduleService.cs"

53E6540C-7C2B-4706-96B4-EDE4840EBD41.sonar.coverage.exclusions=**/ScheduleService.cs
53E6540C-7C2B-4706-96B4-EDE4840EBD41.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\.sonarqube\\out\\1"
53E6540C-7C2B-4706-96B4-EDE4840EBD41.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\.sonarqube\\out\\1\\Issues.json"

53E6540C-7C2B-4706-96B4-EDE4840EBD41.sonar.working.directory=C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\.sonarqube\\out\\.sonar\\mod1
C03FC586-A504-4F8B-A44E-4B661775C2D2.sonar.projectKey=ScheduleMicroserviceBackend:C03FC586-A504-4F8B-A44E-4B661775C2D2
C03FC586-A504-4F8B-A44E-4B661775C2D2.sonar.projectName=ScheduleMicroservice
C03FC586-A504-4F8B-A44E-4B661775C2D2.sonar.projectBaseDir=C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\ScheduleMicroservice
C03FC586-A504-4F8B-A44E-4B661775C2D2.sonar.sourceEncoding=utf-8
C03FC586-A504-4F8B-A44E-4B661775C2D2.sonar.sources=\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\ScheduleMicroservice\\Controllers\\SchedulesController.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\ScheduleMicroservice\\Middleware\\ExceptionHandlingMiddleware.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\ScheduleMicroservice\\Program.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\ScheduleMicroservice\\obj\\Debug\\net7.0\\ScheduleMicroservice.GlobalUsings.g.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\ScheduleMicroservice\\obj\\Debug\\net7.0\\.NETCoreApp,Version=v7.0.AssemblyAttributes.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\ScheduleMicroservice\\obj\\Debug\\net7.0\\ScheduleMicroservice.AssemblyInfo.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\ScheduleMicroservice\\obj\\Debug\\net7.0\\ScheduleMicroservice.MvcApplicationPartsAssemblyInfo.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\ScheduleMicroservice\\appsettings.Development.json",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\ScheduleMicroservice\\appsettings.json",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\ScheduleMicroservice\\Logs\\log.txt",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\ScheduleMicroservice\\Properties\\launchSettings.json"

C03FC586-A504-4F8B-A44E-4B661775C2D2.sonar.coverage.exclusions=**/ExceptionHandlingMiddleware.cs,**/Program.cs
C03FC586-A504-4F8B-A44E-4B661775C2D2.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\.sonarqube\\out\\2"
C03FC586-A504-4F8B-A44E-4B661775C2D2.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\.sonarqube\\out\\2\\Issues.json"

C03FC586-A504-4F8B-A44E-4B661775C2D2.sonar.working.directory=C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\.sonarqube\\out\\.sonar\\mod2
6A13503B-B684-42F9-B556-B1B124CD1D6D.sonar.projectKey=ScheduleMicroserviceBackend:6A13503B-B684-42F9-B556-B1B124CD1D6D
6A13503B-B684-42F9-B556-B1B124CD1D6D.sonar.projectName=ScheduleMicroserviceTest
6A13503B-B684-42F9-B556-B1B124CD1D6D.sonar.projectBaseDir=C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\ScheduleMicroserviceTest
6A13503B-B684-42F9-B556-B1B124CD1D6D.sonar.sourceEncoding=utf-8
6A13503B-B684-42F9-B556-B1B124CD1D6D.sonar.sources=
6A13503B-B684-42F9-B556-B1B124CD1D6D.sonar.tests=\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\ScheduleMicroserviceTest\\UnitTest1.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\ScheduleMicroserviceTest\\Usings.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\ScheduleMicroserviceTest\\coverage.opencover.xml"

6A13503B-B684-42F9-B556-B1B124CD1D6D.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\.sonarqube\\out\\3"
6A13503B-B684-42F9-B556-B1B124CD1D6D.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\.sonarqube\\out\\3\\Issues.json"

6A13503B-B684-42F9-B556-B1B124CD1D6D.sonar.working.directory=C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\ScheduleMicroservice\\.sonarqube\\out\\.sonar\\mod3
sonar.host.url=http://localhost:9000
sonar.cs.opencover.reportsPaths=./ScheduleMicroserviceTest/coverage.opencover.xml
sonar.visualstudio.enable=false

sonar.modules=5813F101-6DF5-421A-B342-1C8553F9F092,53E6540C-7C2B-4706-96B4-EDE4840EBD41,C03FC586-A504-4F8B-A44E-4B661775C2D2,6A13503B-B684-42F9-B556-B1B124CD1D6D

