sonar.projectKey=UserMicroserviceBackend
sonar.working.directory=C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice
sonar.pullrequest.cache.basepath=C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice

2A7FF675-F700-42BE-A198-356268020FC8.sonar.projectKey=UserMicroserviceBackend:2A7FF675-F700-42BE-A198-356268020FC8
2A7FF675-F700-42BE-A198-356268020FC8.sonar.projectName=DataAccessLayer
2A7FF675-F700-42BE-A198-356268020FC8.sonar.projectBaseDir=C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\DataAccessLayer
2A7FF675-F700-42BE-A198-356268020FC8.sonar.sourceEncoding=utf-8
2A7FF675-F700-42BE-A198-356268020FC8.sonar.sources=\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\DataAccessLayer\\CustomDateSerializer.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\DataAccessLayer\\DataBase\\DataBaseSettings.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\DataAccessLayer\\DataBase\\IDataBaseSettings.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\DataAccessLayer\\MappingConfig.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\DataAccessLayer\\Models\\DTO\\LoginRequestDto.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\DataAccessLayer\\Models\\DTO\\LoginResponseDto.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\DataAccessLayer\\Models\\DTO\\PatientDto.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\DataAccessLayer\\Models\\DTO\\PatientRegisterDTO.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\DataAccessLayer\\Models\\Patient.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\DataAccessLayer\\PatientMapping.cs"

2A7FF675-F700-42BE-A198-356268020FC8.sonar.coverage.exclusions=**/PatientMapping.cs,**/MappingConfig.cs,**/CustomDateSerializer.cs,**/DataBaseSettings.cs,**/Patient.cs
2A7FF675-F700-42BE-A198-356268020FC8.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\.sonarqube\\out\\0"
2A7FF675-F700-42BE-A198-356268020FC8.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\.sonarqube\\out\\0\\Issues.json"

2A7FF675-F700-42BE-A198-356268020FC8.sonar.working.directory=C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\.sonarqube\\out\\.sonar\\mod0
3EF0FE65-4559-411B-8F60-678EE435047D.sonar.projectKey=UserMicroserviceBackend:3EF0FE65-4559-411B-8F60-678EE435047D
3EF0FE65-4559-411B-8F60-678EE435047D.sonar.projectName=BusinessLogicLayer
3EF0FE65-4559-411B-8F60-678EE435047D.sonar.projectBaseDir=C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\BusinessLogicLayer
3EF0FE65-4559-411B-8F60-678EE435047D.sonar.sourceEncoding=utf-8
3EF0FE65-4559-411B-8F60-678EE435047D.sonar.sources=\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\BusinessLogicLayer\\Services\\IServices\\IUserService.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\BusinessLogicLayer\\Services\\UserService.cs"

3EF0FE65-4559-411B-8F60-678EE435047D.sonar.coverage.exclusions=**/UserService.cs
3EF0FE65-4559-411B-8F60-678EE435047D.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\.sonarqube\\out\\1"
3EF0FE65-4559-411B-8F60-678EE435047D.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\.sonarqube\\out\\1\\Issues.json"

3EF0FE65-4559-411B-8F60-678EE435047D.sonar.working.directory=C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\.sonarqube\\out\\.sonar\\mod1
384E2058-7D35-4C2C-952F-4264FD523F6F.sonar.projectKey=UserMicroserviceBackend:384E2058-7D35-4C2C-952F-4264FD523F6F
384E2058-7D35-4C2C-952F-4264FD523F6F.sonar.projectName=UserMicroservice
384E2058-7D35-4C2C-952F-4264FD523F6F.sonar.projectBaseDir=C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\UserMicroservice
384E2058-7D35-4C2C-952F-4264FD523F6F.sonar.sourceEncoding=utf-8
384E2058-7D35-4C2C-952F-4264FD523F6F.sonar.sources=\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\UserMicroservice\\Controllers\\UsersController.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\UserMicroservice\\Middleware\\ExceptionHandlingMiddleware.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\UserMicroservice\\Program.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\UserMicroservice\\obj\\Debug\\net7.0\\UserMicroservice.GlobalUsings.g.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\UserMicroservice\\obj\\Debug\\net7.0\\.NETCoreApp,Version=v7.0.AssemblyAttributes.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\UserMicroservice\\obj\\Debug\\net7.0\\UserMicroservice.AssemblyInfo.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\UserMicroservice\\obj\\Debug\\net7.0\\UserMicroservice.MvcApplicationPartsAssemblyInfo.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\UserMicroservice\\appsettings.Development.json",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\UserMicroservice\\appsettings.json",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\UserMicroservice\\Logs\\log.txt",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\UserMicroservice\\Properties\\launchSettings.json"

384E2058-7D35-4C2C-952F-4264FD523F6F.sonar.coverage.exclusions=**/ExceptionHandlingMiddleware.cs,**/Program.cs
384E2058-7D35-4C2C-952F-4264FD523F6F.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\.sonarqube\\out\\2"
384E2058-7D35-4C2C-952F-4264FD523F6F.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\.sonarqube\\out\\2\\Issues.json"

384E2058-7D35-4C2C-952F-4264FD523F6F.sonar.working.directory=C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\.sonarqube\\out\\.sonar\\mod2
627E0920-A442-4728-9929-610EB7538C4C.sonar.projectKey=UserMicroserviceBackend:627E0920-A442-4728-9929-610EB7538C4C
627E0920-A442-4728-9929-610EB7538C4C.sonar.projectName=UserMicroServiceTest
627E0920-A442-4728-9929-610EB7538C4C.sonar.projectBaseDir=C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\UserMicroServiceTest
627E0920-A442-4728-9929-610EB7538C4C.sonar.sourceEncoding=utf-8
627E0920-A442-4728-9929-610EB7538C4C.sonar.sources=
627E0920-A442-4728-9929-610EB7538C4C.sonar.tests=\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\UserMicroServiceTest\\UserControllerTests.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\UserMicroServiceTest\\Usings.cs",\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\UserMicroServiceTest\\coverage.opencover.xml"

627E0920-A442-4728-9929-610EB7538C4C.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\.sonarqube\\out\\3"
627E0920-A442-4728-9929-610EB7538C4C.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\.sonarqube\\out\\3\\Issues.json"

627E0920-A442-4728-9929-610EB7538C4C.sonar.working.directory=C:\\Users\\921611\\source\\repos\\Clinic Visit Appointment Booking System\\UserMicroservice\\.sonarqube\\out\\.sonar\\mod3
sonar.host.url=http://localhost:9000
sonar.cs.opencover.reportsPaths=./UserMicroServiceTest/coverage.opencover.xml
sonar.visualstudio.enable=false

sonar.modules=2A7FF675-F700-42BE-A198-356268020FC8,3EF0FE65-4559-411B-8F60-678EE435047D,384E2058-7D35-4C2C-952F-4264FD523F6F,627E0920-A442-4728-9929-610EB7538C4C

