sonar.host.url=http://localhost:9000
sonar.login=admin
sonar.login=c63e480923076a0d71f59885aa765d5638337b6d
sonar.projectKey=ClinicVisitAngular
sonar.projectName=ClinicVisitAngular
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.exclusions=**/node_modules/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=src/coverage/PROJECT_NAME/lcov.info
sonar.testExecutionReportPaths=reports/sonarqube_report.xml
sonar.javascript.lcov.reportPaths=coverage/lcov-report/lcov.info
sonar.exclusions=src/app/test/**,src/app/app-routing.module.ts,src/main.ts,src/test.ts,src/environments/environment.prod.ts,src/app/login/login.component.ts,src/app/appointmentstatus/appointmentstatus.component.ts,src/app/clinicslist/clinicslist.component.ts,src/app/schedulevisit/schedulevisit.component.ts,src/app/signup/signup.component.ts,src/app/services/token-interceptor.service.ts,src/environments/environment.ts,src/app/navbar/navbar.component.ts,src/app/servicetypes/servicetypes.component.ts,src/app/services/auth.guard.ts,src/app/app.module.ts